// <auto-generated />
namespace DM.AbpZeroTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_IsDefault_To_Template_AND_Added_ChannelTemplateIdANDContentTemplateId_To_Channel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_IsDefault_To_Template_AND_Added_ChannelTemplateIdANDContentTemplateId_To_Channel));
        
        string IMigrationMetadata.Id
        {
            get { return "201605200731490_Added_IsDefault_To_Template_AND_Added_ChannelTemplateIdANDContentTemplateId_To_Channel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
