// <auto-generated />
namespace DM.AbpZeroTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_AppId_To_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_AppId_To_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201604260950199_Added_AppId_To_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
